### ISSUE TITLE
Add self reported degree requirements list

### ISSUE THREAD

**Issue by oluthje** [SlugPath/SlugPath#163] opened 2023-11-30 01:01 UTC
Students can add their enrolled courses to their Degree Requirements list. This is so that the student can keep track of their own degree requirements and track their progress.

This work is exploratory and may not be added if it either doesn't make sense or isn't accomplishable.

**Comment by fercevik729** [comment] 2024-02-24 06:56
Closed as duplicate of #235

**Closed by fercevik729** 2024-02-24 06:56 UTC
Labels: type: duplicate, category: frontend, category: backend, type: refactor, type: feature
